name: Build

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

defaults:
 run:
  shell: bash

jobs:
  build:
    name: Lint, Build, Test
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.bump_version.outputs.tag }}
    steps:
      - uses: actions/checkout@v2

      - name: Lint Code
        run: |
          make lint

      - name: Build Container
        run: |
          make build

      - name: Trivy Image Vulnerability Scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: membrane-app:latest
          severity: 'HIGH,CRITICAL'
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results.sarif'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v1
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'

      - name: Install Inspec for Image Tests
        uses: actionshub/chef-install@main
        if: always()
        with:
          channel: current
          project: inspec

      - name: Run Inspec Tests
        env:
          CHEF_LICENSE: accept
        run: |
          make inspec
          make cleanup

      - name: Publish Inspec Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          check_name: "Inspec Test Results"
          files: test-output/inspec.xml

      - name: Unit Test & Coverage
        run: |
          make unit-coverage

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          check_name: "PHP Unit Test Results"
          files: test-output/unit.xml

      - name: Publish Report
        uses: danhunsaker/clover-reporter-action@v0.2.17-clover
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          clover-file: "test-output/clover.xml"

      - name: Check & Publish Report
        uses: johanvanhelden/gha-clover-test-coverage-check@v1
        with:
          percentage: "45"
          filename: "test-output/clover.xml"

      - name: Functional Test
        run: |
          make functional

      - name: Publish Functional Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          check_name: "PHP Functional Test Results"
          files: test-output/functional.xml
