name: Build

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

defaults:
 run:
  shell: bash

jobs:
  build:
    name: Lint, Build, Analyse, Test
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.bump_version.outputs.tag }}
    steps:
      - uses: actions/checkout@v2

      - name: Set Permissions on Test Output Folder
        run: |
          chmod -R 0777 test-output

      - name: Lint Code
        run: |
          make lint

      - name: Build Container
        run: |
          make build

      - name: Install Inspec for Image Tests
        uses: actionshub/chef-install@main
        if: always()
        with:
          channel: current
          project: inspec

      - name: Run Inspec Tests
        env:
          CHEF_LICENSE: accept
        run: |
          make inspec
          make cleanup

      - name: Publish Inspec Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: ${{ always() }}
        with:
          check_name: "Inspec Test Results"
          files: test-output/inspec.xml

      - name: Static Analysis
        run: |
          make phpstan

      - name: Unit Test & Coverage
        run: |
          make unit-coverage

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: ${{ always() }}
        with:
          check_name: "PHP Unit Test Results"
          files: test-output/unit.xml

      - name: Coverage Report
        uses: lucassabreu/comment-coverage-clover@main
        with:
          file: "test-output/clover.xml"
          min-line-coverage: 47
          min-method-coverage: 44

      - name: Repoint unit & coverage results paths for SonarQube
        run: |
          sudo sed -i 's/\/var\/www\///g' test-output/clover.xml
          sudo sed -i 's/\/var\/www\///g' test-output/unit.xml

      - name: Run SonarQube
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: Functional Test
        run: |
          make functional

      - name: Publish Functional Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: ${{ always() }}
        with:
          check_name: "PHP Functional Test Results"
          files: test-output/functional.xml

      - name: Extract branch name
        run: |
          if [ "${{ github.head_ref }}" == "" ]; then
            echo BRANCH_NAME=main >> $GITHUB_ENV
          else
            echo BRANCH_NAME=$(echo ${{ github.head_ref }} | sed 's/\//-/g') >> $GITHUB_ENV
          fi
        id: extract_branch

      - name: Bump version
        id: bump_version
        uses: anothrNick/github-tag-action@1.52.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          INITIAL_VERSION: v0.0.1
          DEFAULT_BUMP: minor
          PRERELEASE: true
          PRERELEASE_SUFFIX: ${{ env.BRANCH_NAME }}
          RELEASE_BRANCHES: main
          WITH_V: true

      - name: Tag Container
        env:
          ECR_REGISTRY: 311462405659
          MEMBRANE_ECR_REPOSITORY: sirius/membrane-app
        run: |
          docker tag membrane-app:latest $ECR_REGISTRY/$MEMBRANE_ECR_REPOSITORY:${{ steps.bump_version.outputs.tag }}

      - name: Trivy Image Vulnerability Scanner
        uses: aquasecurity/trivy-action@master
        env:
          ECR_REGISTRY: 311462405659
          MEMBRANE_ECR_REPOSITORY: sirius/membrane-app
        with:
          image-ref: ${{ env.ECR_REGISTRY }}/${{ env.MEMBRANE_ECR_REPOSITORY }}:${{ steps.bump_version.outputs.tag }}
          severity: 'HIGH,CRITICAL'
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results.sarif'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_ACTIONS }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ACTIONS }}
          aws-region: eu-west-1
          role-to-assume: arn:aws:iam::311462405659:role/sirius-actions-ci
          role-duration-seconds: 3600
          role-session-name: GitHubActions

      - name: ECR Login
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registries: 311462405659

      - name: Push Container
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          MEMBRANE_ECR_REPOSITORY: sirius/membrane-app
        run: |
          docker tag membrane-app:latest $ECR_REGISTRY/$MEMBRANE_ECR_REPOSITORY:${{ steps.bump_version.outputs.tag }}
          if [ $BRANCH_NAME == "main" ]; then
            docker tag membrane-app:latest $ECR_REGISTRY/$MEMBRANE_ECR_REPOSITORY:latest
            docker tag membrane-app:latest $ECR_REGISTRY/$MEMBRANE_ECR_REPOSITORY:main-${{ steps.bump_version.outputs.tag }}
            # We want all of the tags pushed
            docker push --all-tags $ECR_REGISTRY/$MEMBRANE_ECR_REPOSITORY
          else
            docker push $ECR_REGISTRY/$MEMBRANE_ECR_REPOSITORY:${{ steps.bump_version.outputs.tag }}
          fi

  push-version:
    name: Push Version to Parameter Store & Trigger Deploy
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_ACTIONS }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ACTIONS }}
          aws-region: eu-west-1
          role-to-assume: arn:aws:iam::997462338508:role/sirius-actions-ci
          role-duration-seconds: 3600
          role-session-name: GitHubActions

      - name: Install AWS CLI
        id: install-aws-cli
        uses: unfor19/install-aws-cli-action@v1

      - name: Push Tag to Parameter Store
        run: |
          aws ssm put-parameter --name "opg-sirius-membrane-latest-green-build" --type "String" --value "${{ needs.build.outputs.tag}}" --overwrite --region=eu-west-1

      - name: Trigger Dev Deploy
        shell: bash
        run: curl -u ${{ secrets.JENKINS_API_USER }}:${{ secrets.JENKINS_API_TOKEN }} "https://${{ secrets.JENKINS_URL }}/job/Sirius/job/Deploy_to_Development/build?token=${{ secrets.JENKINS_API_TOKEN_NAME }}&cause=Triggered+by+opg-sirius-membrane"
